### ISSUE TITLE
An Exception throwing "A call to SSPI failed, see inner exception"

### ISSUE THREAD

**Issue by npsumesh** [ademar/EppLib.NET#8]
Hi,
An Exception throwing when connecting to Epp Server using EppLib
   stream.AuthenticateAsClient(EPP_REGISTRY_COM, clientCertificates, SslProtocols.Tls, false);
How to solve this issue...?

**Comment by ademar** [comment]
What does the inner exception says ?

**Comment by npsumesh** [comment]
The inner exception is
{"The message received was unexpected or badly formatted"}

I converted the certificates to .pfx file (my_certificate.pem+ my_private_key.pem+ ca_certificate.pem)

**Comment by ademar** [comment]
It is possible the certificate has not been converted properly? See the following article:

http://stackoverflow.com/questions/808669/convert-a-cert-pem-certificate-to-a-pfx-certificate

Also you only need to provide a certificate if the registry requires you to present a client certificate which most registries do not.

Which registry' server are you connecting to ?

**Comment by npsumesh** [comment]
.QA Registry ,
I created a csr certificate and Privatekey using openssl, and they(Registry) send the signed certificate and ca certificate.And i connected through OPenSSL using these three certificates and connected.
openssl.exe s_client -connect ote.registry.qa:700 -tls1 -cert epp-cert.pem -key epp-key.pem -CAfile cacert.pem

By using these commands its worked.

I have one doubt about the conversion of the certificates to .pfx file
The conversion of file with two certificate(signed certificate and ca certificate) Or three certificate (signed certificate, my private key and ca certificate)...?

**Comment by ademar** [comment]
I think it shouldn't matter if you include the CA certificate or not. I do have found sometimes the order in which they are concatenated it does matter - depends on the server.

Are you running this on Mono or Windows ?

**Comment by npsumesh** [comment]
im running on windows

Using this command i converted the certificates to .pfx
openssl pkcs12 -export -out epp.pfx -inkey epp-key.pem -in certificate.crt -certfile cacert.pem

**Comment by ademar** [comment]
When you created the PFX you had to provide a password, right ?

Are you passing that password when opening the certificate ?

```csharp
var clientCertificate = new X509Certificate(@"D:\path_to_cert\cert.pfx", "password");
```

**Comment by npsumesh** [comment]
yes, provided the password and also written the password in code.

**Comment by ademar** [comment]
I'm running out of ideas. I have seen this message in the past but do not recall what was the problem.

**Comment by npsumesh** [comment]
when i test through openssl its working fine...

**Comment by ademar** [comment]
> Please give me a solution for this....

Sorry, I've tried to help but ultimately this is not a problem of the library. You are barking at the wrong tree.
